(function (global) {
  "use strict";

  const STORAGE_KEY = "yu-lab-primer-library-v1";
  const GITHUB_REPOSITORY = "YanWang-whu/Yu-Jin-Lab-Database";
  const GITHUB_BRANCH = "main";
  const GITHUB_LIBRARY_PATH = "primer_library.json";
  const BASES = /[ACGTNRYKMSWBDHVUacgtnrykmswbdhvu]/g;
  const COMPLEMENT = { A: "T", C: "G", G: "C", T: "A", U: "A", N: "N", R: "Y", Y: "R", K: "M", M: "K", S: "S", W: "W", B: "V", D: "H", H: "D", V: "B" };

  function escapeHtml(value) { return String(value ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;"); }
  function normalizeName(value) { return String(value ?? "").trim().replace(/\s+/g, " ").toLocaleLowerCase(); }
  function sanitizePrimerSequence(value) { const matches = String(value ?? "").match(BASES); return matches ? matches.join("").toUpperCase().replaceAll("U", "T") : ""; }
  function sanitizeInputSequence(value) { return sanitizePrimerSequence(String(value ?? "").split(/\r?\n/).filter((line) => !line.trim().startsWith(">")).join("")); }
  function reverseComplement(seq) { let out = ""; for (let index = seq.length - 1; index >= 0; index -= 1) out += COMPLEMENT[seq[index]] || "N"; return out; }
  function calculateTm(seq) { const clean = sanitizePrimerSequence(seq); if (!clean || /[^ACGT]/.test(clean)) return ""; const gc = (clean.match(/[GC]/g) || []).length; const at = clean.length - gc; const tm = clean.length < 14 ? 2 * at + 4 * gc : 64.9 + (41 * (gc - 16.4)) / clean.length; return tm.toFixed(1); }
  function splitSegments(seq, parts) { const count = Math.max(1, Math.min(parts, seq.length)); const base = Math.floor(seq.length / count); let extra = seq.length % count; let offset = 0; const segments = []; for (let index = 0; index < count; index += 1) { const length = base + (extra > 0 ? 1 : 0); extra -= 1; segments.push({ value: seq.slice(offset, offset + length), offset, length }); offset += length; } return segments; }
  function countMismatches(target, sequence, start, maxMismatches) { let count = 0; const positions = []; for (let index = 0; index < target.length; index += 1) { const observed = sequence[start + index]; if (target[index] !== observed) { count += 1; positions.push({ primerPos: index + 1, sequencePos: start + index + 1, expected: target[index], observed }); if (count > maxMismatches) break; } } return { count, positions }; }
  function mismatchClass(count) { if (count <= 0) return "exact"; if (count === 1) return "one"; return "two"; }

  async function findPrimerMatches(sequence, primers, options = {}) {
    const maxMismatches = Math.max(0, Math.min(2, Number(options.maxMismatches ?? 0)));
    const limit = Math.max(1, Number(options.limit ?? 5000));
    const onProgress = typeof options.onProgress === "function" ? options.onProgress : null;
    const index = new Map();
    const seedLengths = new Set();
    let searchablePrimerCount = 0;
    primers.forEach((primer, primerIndex) => {
      const primerSeq = sanitizePrimerSequence(primer.sequence);
      if (!primerSeq || /[^ACGT]/.test(primerSeq)) return;
      searchablePrimerCount += 1;
      [{ orientation: "+", arrow: "→", target: primerSeq }, { orientation: "-", arrow: "←", target: reverseComplement(primerSeq) }].forEach((entry) => {
        splitSegments(entry.target, maxMismatches + 1).forEach((segment) => {
          if (!segment.value) return;
          const key = `${segment.length}:${segment.value}`;
          if (!index.has(key)) index.set(key, []);
          index.get(key).push({ primer, primerIndex, primerSeq, orientation: entry.orientation, arrow: entry.arrow, target: entry.target, offset: segment.offset });
          seedLengths.add(segment.length);
        });
      });
    });
    const matches = [];
    const seen = new Set();
    const lengths = Array.from(seedLengths).sort((a, b) => a - b);
    let scanned = 0;
    for (const seedLength of lengths) {
      if (seedLength > sequence.length) continue;
      const maxStart = sequence.length - seedLength;
      for (let position = 0; position <= maxStart; position += 1) {
        const candidates = index.get(`${seedLength}:${sequence.slice(position, position + seedLength)}`);
        if (candidates) {
          for (const candidate of candidates) {
            const start = position - candidate.offset;
            const end = start + candidate.target.length;
            if (start < 0 || end > sequence.length) continue;
            const hitKey = `${candidate.primer.id || candidate.primerIndex}|${candidate.orientation}|${start}`;
            if (seen.has(hitKey)) continue;
            seen.add(hitKey);
            const mismatch = countMismatches(candidate.target, sequence, start, maxMismatches);
            if (mismatch.count <= maxMismatches) {
              matches.push({ primerId: candidate.primer.id, primerName: candidate.primer.name, primerSequence: candidate.primerSeq, target: candidate.target, orientation: candidate.orientation, arrow: candidate.arrow, start, end, start1: start + 1, end1: end, length: candidate.target.length, mismatches: mismatch.count, mismatchPositions: mismatch.positions, box: candidate.primer.box || "", tm: candidate.primer.tm || "", remarks: candidate.primer.remarks || "" });
              if (matches.length >= limit) { matches.sort((a, b) => a.start - b.start || a.end - b.end || a.primerName.localeCompare(b.primerName)); return { matches, truncated: true, searchablePrimerCount }; }
            }
          }
        }
        scanned += 1;
        if (onProgress && scanned % 250000 === 0) { onProgress({ scanned, seedLength, matches: matches.length }); await new Promise((resolve) => setTimeout(resolve, 0)); }
      }
    }
    matches.sort((a, b) => a.start - b.start || a.end - b.end || a.primerName.localeCompare(b.primerName));
    return { matches, truncated: false, searchablePrimerCount };
  }

  const Core = { sanitizePrimerSequence, sanitizeInputSequence, reverseComplement, calculateTm, splitSegments, countMismatches, findPrimerMatches };
  if (typeof module !== "undefined" && module.exports) module.exports = Core;
  global.PrimerMatcherCore = Core;
  if (!global.document) return;

  let defaultPayload = global.PRIMER_LIBRARY_DEFAULTS || { metadata: {}, primers: [] };
  const state = { primers: [], matches: [], selectedMatchIndex: -1, currentSequence: "", currentSequenceName: "Input sequence", librarySource: "内置库", lastTruncated: false };
  const el = {
    libraryMeta: document.getElementById("libraryMeta"), tabs: Array.from(document.querySelectorAll(".tab")), views: Array.from(document.querySelectorAll(".view")), sequenceName: document.getElementById("sequenceName"), sequenceInput: document.getElementById("sequenceInput"), clearSequenceBtn: document.getElementById("clearSequenceBtn"), mismatchSelect: document.getElementById("mismatchSelect"), resultLimit: document.getElementById("resultLimit"), runMatchBtn: document.getElementById("runMatchBtn"), metricSeqLen: document.getElementById("metricSeqLen"), metricPrimerCount: document.getElementById("metricPrimerCount"), metricHitCount: document.getElementById("metricHitCount"), metricStatus: document.getElementById("metricStatus"), overviewCanvas: document.getElementById("overviewCanvas"), resultsBody: document.getElementById("resultsBody"), resultFilter: document.getElementById("resultFilter"), hitDetail: document.getElementById("hitDetail"), primerFilter: document.getElementById("primerFilter"), primerBody: document.getElementById("primerBody"), primerTableFoot: document.getElementById("primerTableFoot"), exportCsvBtn: document.getElementById("exportCsvBtn"), exportJsonBtn: document.getElementById("exportJsonBtn"), primerForm: document.getElementById("primerForm"), editPrimerId: document.getElementById("editPrimerId"), primerName: document.getElementById("primerName"), primerSequence: document.getElementById("primerSequence"), primerBox: document.getElementById("primerBox"), primerTm: document.getElementById("primerTm"), primerRemarks: document.getElementById("primerRemarks"), newPrimerBtn: document.getElementById("newPrimerBtn"), deletePrimerBtn: document.getElementById("deletePrimerBtn"), pasteBox: document.getElementById("pasteBox"), mergePasteBtn: document.getElementById("mergePasteBtn"), replacePasteBtn: document.getElementById("replacePasteBtn"), pasteStatus: document.getElementById("pasteStatus"), resetLibraryBtn: document.getElementById("resetLibraryBtn"), githubToken: document.getElementById("githubToken"), githubCommitMessage: document.getElementById("githubCommitMessage"), publishGithubBtn: document.getElementById("publishGithubBtn"), githubPublishStatus: document.getElementById("githubPublishStatus"), libraryTotal: document.getElementById("libraryTotal"), libraryWithSeq: document.getElementById("libraryWithSeq"), libraryWithoutSeq: document.getElementById("libraryWithoutSeq"), librarySource: document.getElementById("librarySource")
  };

  function clonePrimer(primer) { return { id: primer.id || nextPrimerId(), name: String(primer.name ?? "").trim(), sequence: sanitizePrimerSequence(primer.sequence ?? primer["sequence 5'-3'"] ?? ""), box: String(primer.box ?? primer.Box ?? "").trim(), tm: String(primer.tm ?? primer.Tm ?? "").trim(), remarks: String(primer.remarks ?? primer.note ?? primer.Note ?? "").trim() }; }
  function nextPrimerId() { const max = state.primers.reduce((highest, primer) => { const match = String(primer.id || "").match(/(\d+)$/); return match ? Math.max(highest, Number(match[1])) : highest; }, 0); return `YL${String(max + 1).padStart(4, "0")}`; }
  function primerKey(primer) { return `${normalizeName(primer.name)}|${sanitizePrimerSequence(primer.sequence)}`; }
  async function loadDefaultPayload() { if (!global.fetch) return; try { const response = await fetch(`${GITHUB_LIBRARY_PATH}?v=${Date.now()}`, { cache: "no-store" }); if (!response.ok) return; const payload = await response.json(); if (Array.isArray(payload.primers)) defaultPayload = payload; } catch {} }
  function loadPrimers() { const saved = localStorage.getItem(STORAGE_KEY); if (saved) { try { const parsed = JSON.parse(saved); if (Array.isArray(parsed.primers)) { state.primers = parsed.primers.map(clonePrimer); state.librarySource = "本机已保存"; return; } } catch { localStorage.removeItem(STORAGE_KEY); } } state.primers = (defaultPayload.primers || []).map(clonePrimer); state.librarySource = "内置库"; }
  function savePrimers(sourceLabel = "本机已保存") { localStorage.setItem(STORAGE_KEY, JSON.stringify({ savedAt: new Date().toISOString(), primers: state.primers })); state.librarySource = sourceLabel; }
  function resetLibrary() { state.primers = (defaultPayload.primers || []).map(clonePrimer); localStorage.removeItem(STORAGE_KEY); state.librarySource = "内置库"; clearPrimerForm(); renderAll(); }
  function formatBp(value) { return `${Number(value || 0).toLocaleString()} bp`; }
  function updateLibraryMeta() { const stats = defaultPayload.metadata?.stats; const builtIn = stats ? `${stats.unique_primers} 条内置引物` : `${defaultPayload.primers?.length || 0} 条内置引物`; el.libraryMeta.textContent = `${builtIn} · 当前库 ${state.primers.length} 条 · ${state.librarySource}`; }
  function updateMetrics(status = null) { const seq = sanitizeInputSequence(el.sequenceInput.value); const searchable = state.primers.filter((primer) => primer.sequence && !/[^ACGT]/.test(primer.sequence)).length; el.metricSeqLen.textContent = formatBp(seq.length); el.metricPrimerCount.textContent = String(searchable); el.metricHitCount.textContent = String(state.matches.length); if (status) el.metricStatus.textContent = status; }
  function setTab(name) { el.tabs.forEach((tab) => tab.classList.toggle("active", tab.dataset.tab === name)); el.views.forEach((view) => view.classList.toggle("active", view.id === `view-${name}`)); if (name === "library") renderPrimerTable(); if (name === "update") renderLibraryStatus(); }
  function renderAll() { updateLibraryMeta(); updateMetrics(); renderPrimerTable(); renderLibraryStatus(); renderResults(); drawOverview(); renderHitDetail(); }
  function colorForMismatch(count) { if (count <= 0) return "#0f766e"; if (count === 1) return "#b7791f"; return "#be3a4a"; }
  function drawArrow(ctx, x1, x2, y, color, selected, orientation) { const minWidth = 3; if (Math.abs(x2 - x1) < minWidth) x2 = x1 + (orientation === "+" ? minWidth : -minWidth); ctx.strokeStyle = selected ? "#172126" : color; ctx.fillStyle = selected ? "#172126" : color; ctx.lineWidth = selected ? 4 : 2.5; ctx.beginPath(); ctx.moveTo(x1, y); ctx.lineTo(x2, y); ctx.stroke(); const head = 6; const dir = orientation === "+" ? 1 : -1; const tip = orientation === "+" ? x2 : x1; ctx.beginPath(); ctx.moveTo(tip, y); ctx.lineTo(tip - dir * head, y - head * 0.6); ctx.lineTo(tip - dir * head, y + head * 0.6); ctx.closePath(); ctx.fill(); }
  function drawOverview() { const canvas = el.overviewCanvas; const rect = canvas.getBoundingClientRect(); const dpr = global.devicePixelRatio || 1; const width = Math.max(320, Math.floor(rect.width)); const height = 128; canvas.width = Math.floor(width * dpr); canvas.height = Math.floor(height * dpr); const ctx = canvas.getContext("2d"); ctx.setTransform(dpr, 0, 0, dpr, 0, 0); ctx.clearRect(0, 0, width, height); ctx.fillStyle = "#fbfcfc"; ctx.fillRect(0, 0, width, height); const left = 18; const right = width - 18; const mid = Math.round((left + right) / 2); ctx.strokeStyle = "#b8c6cc"; ctx.lineWidth = 1; ctx.beginPath(); ctx.moveTo(left, 64); ctx.lineTo(right, 64); ctx.stroke(); ctx.fillStyle = "#607079"; ctx.font = "12px Segoe UI, Arial"; const seqLen = state.currentSequence.length; if (!seqLen) { ctx.fillText("0 bp", left, 28); return; } ctx.fillText("1", left, 28); ctx.fillText(String(Math.max(1, Math.round(seqLen / 2)).toLocaleString()), mid - 20, 28); ctx.fillText(seqLen.toLocaleString(), right - 42, 28); [left, mid, right].forEach((x) => { ctx.beginPath(); ctx.moveTo(x, 58); ctx.lineTo(x, 70); ctx.stroke(); }); state.matches.slice(0, 1600).forEach((hit, visibleIndex) => { const originalIndex = state.matches.indexOf(hit); const x1 = left + (hit.start / seqLen) * (right - left); const x2 = left + (hit.end / seqLen) * (right - left); const mismatchOffset = hit.mismatches === 0 ? -8 : hit.mismatches === 1 ? 0 : 8; const jitter = (visibleIndex % 5) - 2; const y = (hit.orientation === "+" ? 46 : 84) + mismatchOffset + jitter; drawArrow(ctx, x1, x2, y, colorForMismatch(hit.mismatches), originalIndex === state.selectedMatchIndex, hit.orientation); }); if (state.lastTruncated) { ctx.fillStyle = "#be3a4a"; ctx.fillText("结果已达到上限", left, 116); } }
  function filteredMatches() { const filter = normalizeName(el.resultFilter.value); if (!filter) return state.matches; return state.matches.filter((hit) => `${hit.primerName} ${hit.box} ${hit.remarks}`.toLocaleLowerCase().includes(filter)); }
  function renderResults() { const rows = filteredMatches(); if (!rows.length) { el.resultsBody.innerHTML = `<tr><td colspan="6" class="muted">暂无命中</td></tr>`; return; } el.resultsBody.innerHTML = rows.map((hit) => { const index = state.matches.indexOf(hit); const cls = index === state.selectedMatchIndex ? "selected" : ""; return `<tr class="${cls}" data-match-index="${index}"><td>${escapeHtml(hit.primerName)}</td><td><strong>${hit.arrow}</strong> ${hit.orientation === "+" ? "同向" : "反向互补"}</td><td>${hit.start1.toLocaleString()}-${hit.end1.toLocaleString()}</td><td><span class="pill ${mismatchClass(hit.mismatches)}">${hit.mismatches}</span></td><td>${escapeHtml(hit.box)}</td><td>${escapeHtml(hit.tm)}</td></tr>`; }).join(""); }
  function renderHitDetail() { const hit = state.matches[state.selectedMatchIndex]; if (!hit) { el.hitDetail.className = "detail-empty"; el.hitDetail.innerHTML = "暂无选中命中"; return; } el.hitDetail.className = ""; const genomic = state.currentSequence.slice(hit.start, hit.end); const mismatchSet = new Set(hit.mismatchPositions.map((item) => item.primerPos - 1)); const targetHtml = hit.target.split("").map((base, index) => `<span class="base ${mismatchSet.has(index) ? "mismatch" : ""}">${base}</span>`).join(""); const genomicHtml = genomic.split("").map((base, index) => `<span class="base ${mismatchSet.has(index) ? "mismatch" : ""}">${base}</span>`).join(""); const markerHtml = hit.target.split("").map((_, index) => `<span class="base">${mismatchSet.has(index) ? "^" : "|"}</span>`).join(""); const mismatchText = hit.mismatchPositions.length ? hit.mismatchPositions.map((item) => `${item.sequencePos}:${item.expected}>${item.observed}`).join(", ") : "无"; el.hitDetail.innerHTML = `<div class="hit-title"><div><strong>${escapeHtml(hit.primerName)}</strong><div class="muted">${escapeHtml(hit.box || "Box 空")}</div></div><span class="pill ${mismatchClass(hit.mismatches)}">${hit.mismatches}</span></div><dl class="kv"><dt>位置</dt><dd>${hit.start1.toLocaleString()}-${hit.end1.toLocaleString()}</dd><dt>方向</dt><dd>${hit.arrow} ${hit.orientation === "+" ? "同向" : "反向互补"}</dd><dt>Tm</dt><dd>${escapeHtml(hit.tm || "")}</dd><dt>错配</dt><dd>${escapeHtml(mismatchText)}</dd><dt>备注</dt><dd>${escapeHtml(hit.remarks || "")}</dd></dl><div class="alignment"><div class="alignment-row"><span>目标</span><code>${targetHtml}</code></div><div class="alignment-row"><span></span><code>${markerHtml}</code></div><div class="alignment-row"><span>输入</span><code>${genomicHtml}</code></div></div>`; }
  async function runMatch() { const sequence = sanitizeInputSequence(el.sequenceInput.value); state.currentSequence = sequence; state.currentSequenceName = el.sequenceName.value.trim() || "Input sequence"; state.matches = []; state.selectedMatchIndex = -1; state.lastTruncated = false; updateMetrics(sequence ? "匹配中" : "无序列"); renderResults(); drawOverview(); renderHitDetail(); if (!sequence) return; el.runMatchBtn.disabled = true; try { const result = await findPrimerMatches(sequence, state.primers, { maxMismatches: Number(el.mismatchSelect.value), limit: Number(el.resultLimit.value), onProgress: ({ matches }) => { el.metricStatus.textContent = `匹配中 ${matches}`; } }); state.matches = result.matches; state.lastTruncated = result.truncated; state.selectedMatchIndex = state.matches.length ? 0 : -1; updateMetrics(result.truncated ? "达到上限" : "完成"); renderResults(); drawOverview(); renderHitDetail(); } finally { el.runMatchBtn.disabled = false; } }
  function renderPrimerTable() { const filter = normalizeName(el.primerFilter.value); const rows = state.primers.filter((primer) => !filter || `${primer.name} ${primer.sequence} ${primer.box} ${primer.remarks}`.toLocaleLowerCase().includes(filter)); const visible = rows.slice(0, 600); el.primerBody.innerHTML = visible.map((primer) => `<tr><td>${escapeHtml(primer.name)}</td><td class="sequence">${escapeHtml(primer.sequence)}</td><td>${escapeHtml(primer.box)}</td><td>${escapeHtml(primer.tm)}</td><td>${escapeHtml(primer.remarks)}</td><td><button type="button" data-edit-id="${escapeHtml(primer.id)}">编辑</button></td></tr>`).join(""); el.primerTableFoot.textContent = `显示 ${visible.length} / ${rows.length} 条；当前库共 ${state.primers.length} 条`; }
  function renderLibraryStatus() { const withSeq = state.primers.filter((primer) => primer.sequence).length; el.libraryTotal.textContent = String(state.primers.length); el.libraryWithSeq.textContent = String(withSeq); el.libraryWithoutSeq.textContent = String(state.primers.length - withSeq); el.librarySource.textContent = state.librarySource; }
  function clearPrimerForm() { el.editPrimerId.value = ""; el.primerName.value = ""; el.primerSequence.value = ""; el.primerBox.value = ""; el.primerTm.value = ""; el.primerRemarks.value = ""; el.deletePrimerBtn.disabled = true; }
  function editPrimer(id) { const primer = state.primers.find((item) => item.id === id); if (!primer) return; el.editPrimerId.value = primer.id; el.primerName.value = primer.name; el.primerSequence.value = primer.sequence; el.primerBox.value = primer.box; el.primerTm.value = primer.tm; el.primerRemarks.value = primer.remarks; el.deletePrimerBtn.disabled = false; setTab("update"); }
  function submitPrimer(event) { event.preventDefault(); const sequence = sanitizePrimerSequence(el.primerSequence.value); const primer = { id: el.editPrimerId.value || nextPrimerId(), name: el.primerName.value.trim(), sequence, box: el.primerBox.value.trim(), tm: el.primerTm.value.trim() || calculateTm(sequence), remarks: el.primerRemarks.value.trim() }; if (!primer.name && !primer.sequence) return; const existingIndex = state.primers.findIndex((item) => item.id === primer.id); if (existingIndex >= 0) state.primers[existingIndex] = primer; else state.primers.push(primer); savePrimers(); clearPrimerForm(); renderAll(); }
  function deleteCurrentPrimer() { const id = el.editPrimerId.value; if (!id) return; const primer = state.primers.find((item) => item.id === id); if (!primer) return; if (!global.confirm(`删除 ${primer.name || primer.sequence} ?`)) return; state.primers = state.primers.filter((item) => item.id !== id); savePrimers(); clearPrimerForm(); renderAll(); }
  function normalizeHeader(value) { return String(value ?? "").trim().toLocaleLowerCase().replace(/\s+/g, " "); }
  function findColumn(headers, tests, fallback) { const index = headers.findIndex((header) => tests.some((test) => test(header))); return index >= 0 ? index : fallback; }
  function parsePastedTable(textValue) { const lines = String(textValue ?? "").replace(/\r/g, "").split("\n").filter((line) => line.trim()); if (!lines.length) return []; const rows = lines.map((line) => (line.includes("\t") ? line.split("\t") : line.split(","))); const headerCandidate = rows[0].map(normalizeHeader); const hasHeader = headerCandidate.some((header) => header === "name" || header.includes("sequence") || header.includes("seq") || header.includes("box") || header.includes("tm") || header.includes("备注")); const headers = hasHeader ? headerCandidate : []; const startRow = hasHeader ? 1 : 0; const nameCol = hasHeader ? findColumn(headers, [(h) => h === "name", (h) => h.includes("primer"), (h) => h.includes("引物")], 0) : 0; const seqCol = hasHeader ? findColumn(headers, [(h) => h.includes("sequence"), (h) => h === "seq", (h) => h.includes("5"), (h) => h.includes("序列")], 1) : 1; const boxCol = hasHeader ? findColumn(headers, [(h) => h === "box", (h) => h.includes("location"), (h) => h.includes("位置")], 2) : 2; const tmCol = hasHeader ? findColumn(headers, [(h) => h === "tm", (h) => h.includes("tm")], 3) : 3; const remarksCol = hasHeader ? findColumn(headers, [(h) => h.includes("remark"), (h) => h.includes("note"), (h) => h.includes("备注")], 4) : 4; const locationHeader = hasHeader && headers[boxCol] && headers[boxCol].includes("location"); let currentBox = ""; const parsed = []; for (let rowIndex = startRow; rowIndex < rows.length; rowIndex += 1) { const row = rows[rowIndex].map((cell) => String(cell ?? "").trim()); const joined = row.join(" "); const boxMatch = joined.match(/box\s*([0-9]+)/i); if (boxMatch) currentBox = `Box ${boxMatch[1]}`; const name = row[nameCol] || ""; const sequence = sanitizePrimerSequence(row[seqCol] || ""); if (!name && !sequence) continue; const rawBox = row[boxCol] || ""; const box = locationHeader && currentBox && rawBox ? `${currentBox} / ${rawBox}` : rawBox || currentBox; const tm = row[tmCol] || calculateTm(sequence); parsed.push({ id: nextPrimerId(), name, sequence, box, tm, remarks: row[remarksCol] || "" }); } return parsed; }
  function mergePrimers(incoming, replace = false) { if (replace) state.primers = []; const keyToIndex = new Map(state.primers.map((primer, index) => [primerKey(primer), index])); let added = 0; let updated = 0; incoming.forEach((primer) => { const clean = clonePrimer(primer); if (!clean.name && !clean.sequence) return; const key = primerKey(clean); if (keyToIndex.has(key)) { const index = keyToIndex.get(key); state.primers[index] = { ...state.primers[index], ...Object.fromEntries(Object.entries(clean).filter(([, value]) => value !== "" && value !== undefined)), id: state.primers[index].id }; updated += 1; } else { clean.id = nextPrimerId(); state.primers.push(clean); keyToIndex.set(key, state.primers.length - 1); added += 1; } }); savePrimers(replace ? "粘贴替换" : "粘贴更新"); renderAll(); return { added, updated, total: incoming.length }; }
  function handlePasteMerge(replace = false) { const parsed = parsePastedTable(el.pasteBox.value); const summary = mergePrimers(parsed, replace); el.pasteStatus.textContent = `读取 ${summary.total} 条，新增 ${summary.added} 条，更新 ${summary.updated} 条`; }
  function csvEscape(value) { const textValue = String(value ?? ""); if (/[",\n]/.test(textValue)) return `"${textValue.replace(/"/g, '""')}"`; return textValue; }
  function exportCsv() { const header = ["name", "sequence 5'-3'", "Box", "Tm", "remarks"]; const rows = state.primers.map((primer) => [primer.name, primer.sequence, primer.box, primer.tm, primer.remarks]); downloadText("yu_lab_primer_library.csv", [header, ...rows].map((row) => row.map(csvEscape).join(",")).join("\n"), "text/csv;charset=utf-8"); }
  function buildLibraryPayload() { const primers = state.primers.map((primer, index) => ({ id: primer.id || `YL${String(index + 1).padStart(4, "0")}`, name: primer.name || "", sequence: sanitizePrimerSequence(primer.sequence || ""), box: primer.box || "", tm: primer.tm || "", remarks: primer.remarks || "" })); return { metadata: { updatedAt: new Date().toISOString(), source: "Yu Lab Primer Matcher website", schema: ["name", "sequence 5'-3'", "Box", "Tm", "remarks"], stats: { unique_primers: primers.length, with_sequence: primers.filter((primer) => primer.sequence).length, without_sequence: primers.filter((primer) => !primer.sequence).length } }, primers }; }
  function exportJson() { downloadText("yu_lab_primer_library.json", JSON.stringify(buildLibraryPayload(), null, 2), "application/json;charset=utf-8"); }
  function utf8ToBase64(textValue) { const bytes = new TextEncoder().encode(textValue); let binary = ""; const chunkSize = 8192; for (let index = 0; index < bytes.length; index += chunkSize) binary += String.fromCharCode(...bytes.slice(index, index + chunkSize)); return btoa(binary); }
  async function fetchGithubLibrarySha(token) { const url = `https://api.github.com/repos/${GITHUB_REPOSITORY}/contents/${GITHUB_LIBRARY_PATH}?ref=${encodeURIComponent(GITHUB_BRANCH)}`; const response = await fetch(url, { headers: { Accept: "application/vnd.github+json", Authorization: `Bearer ${token}` } }); if (response.status === 404) return ""; if (!response.ok) throw new Error(await response.text()); const payload = await response.json(); return payload.sha || ""; }
  async function publishLibraryToGithub() { const token = el.githubToken.value.trim(); if (!token) { el.githubPublishStatus.textContent = "需要 GitHub token"; return; } const message = el.githubCommitMessage.value.trim() || "Update primer library"; const confirmed = global.confirm(`将当前 ${state.primers.length} 条引物提交到 ${GITHUB_REPOSITORY}/${GITHUB_LIBRARY_PATH}。只有你拥有仓库写权限时才会成功。`); if (!confirmed) return; el.publishGithubBtn.disabled = true; el.githubPublishStatus.textContent = "正在读取线上文件"; try { const sha = await fetchGithubLibrarySha(token); const payload = buildLibraryPayload(); const body = { message, branch: GITHUB_BRANCH, content: utf8ToBase64(JSON.stringify(payload, null, 2)) }; if (sha) body.sha = sha; el.githubPublishStatus.textContent = "正在提交到 GitHub"; const response = await fetch(`https://api.github.com/repos/${GITHUB_REPOSITORY}/contents/${GITHUB_LIBRARY_PATH}`, { method: "PUT", headers: { Accept: "application/vnd.github+json", Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify(body) }); if (!response.ok) throw new Error(await response.text()); defaultPayload = payload; localStorage.removeItem(STORAGE_KEY); state.librarySource = "GitHub 已提交"; el.githubPublishStatus.textContent = "提交成功；GitHub Pages 通常会在几十秒到几分钟内更新"; renderAll(); } catch (error) { el.githubPublishStatus.textContent = `提交失败：${error.message || error}`; } finally { el.publishGithubBtn.disabled = false; } }
  function downloadText(filename, content, type) { const blob = new Blob([content], { type }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = filename; document.body.appendChild(link); link.click(); link.remove(); URL.revokeObjectURL(url); }
  function bindEvents() { el.tabs.forEach((tab) => tab.addEventListener("click", () => setTab(tab.dataset.tab))); el.sequenceInput.addEventListener("input", () => updateMetrics()); el.clearSequenceBtn.addEventListener("click", () => { el.sequenceInput.value = ""; state.currentSequence = ""; state.matches = []; state.selectedMatchIndex = -1; updateMetrics("待匹配"); renderResults(); drawOverview(); renderHitDetail(); }); el.runMatchBtn.addEventListener("click", runMatch); el.resultFilter.addEventListener("input", renderResults); el.resultsBody.addEventListener("click", (event) => { const row = event.target.closest("tr[data-match-index]"); if (!row) return; state.selectedMatchIndex = Number(row.dataset.matchIndex); renderResults(); drawOverview(); renderHitDetail(); }); el.overviewCanvas.addEventListener("click", (event) => { if (!state.currentSequence.length || !state.matches.length) return; const rect = el.overviewCanvas.getBoundingClientRect(); const x = event.clientX - rect.left; const left = 18; const right = rect.width - 18; const base = Math.max(0, Math.min(state.currentSequence.length, ((x - left) / (right - left)) * state.currentSequence.length)); let bestIndex = 0; let bestDistance = Infinity; state.matches.forEach((hit, index) => { const center = (hit.start + hit.end) / 2; const distance = Math.abs(center - base); if (distance < bestDistance) { bestDistance = distance; bestIndex = index; } }); state.selectedMatchIndex = bestIndex; renderResults(); drawOverview(); renderHitDetail(); }); global.addEventListener("resize", drawOverview); el.primerFilter.addEventListener("input", renderPrimerTable); el.primerBody.addEventListener("click", (event) => { const button = event.target.closest("button[data-edit-id]"); if (button) editPrimer(button.dataset.editId); }); el.exportCsvBtn.addEventListener("click", exportCsv); el.exportJsonBtn.addEventListener("click", exportJson); el.primerForm.addEventListener("submit", submitPrimer); el.newPrimerBtn.addEventListener("click", clearPrimerForm); el.deletePrimerBtn.addEventListener("click", deleteCurrentPrimer); el.mergePasteBtn.addEventListener("click", () => handlePasteMerge(false)); el.replacePasteBtn.addEventListener("click", () => handlePasteMerge(true)); el.publishGithubBtn.addEventListener("click", publishLibraryToGithub); el.resetLibraryBtn.addEventListener("click", resetLibrary); }
  async function boot() { await loadDefaultPayload(); loadPrimers(); bindEvents(); clearPrimerForm(); renderAll(); }
  boot();
})(typeof window !== "undefined" ? window : globalThis);
